language: python
python:
  - "2.7"

install: "pip install -r requirements.txt --use-mirrors"
# command to run tests, e.g. python setup.py test
script:
  - python test.py

notifications:
  email: false