language: python
python:
  - "2.7"

sudo: required
install: 
  - apt-get install gfortran libopenblas-dev liblapack-dev
  - pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:
  - python test.py

notifications:
  email: false